### ISSUE TITLE
Presentation window and overview window on same screen

### ISSUE THREAD

**Issue by madoar** [pdfpc/pdfpc#151]
Hi,
today I tested pdfpc on my laptop, which also runs on linux mint 17.3 and cinnamon.
I used the current version on the github master for that test, which I built like described with make.
While doing that I discovered, that both pdfpc windows are opened on the same screen.
Both windows were shown on the monitor I plugged in with an mini-displayport to vga adapter.
In addition I also saw the bug reported in #64.
If you need additional information tell me and I'll try to provide it.

Greetings 
Marc

**Comment by simonnagl** [comment]
Hi Marc,
can you test if the bug is not there at 42e9f769990d1eefdcc12e01377f10172aead494?

I think this issue is solved with #64.

**Comment by madoar** [comment]
Hi,
I checked out 42e9f76 with `git checkout 42e9f76` and rebuilt pdfpc with make.
You're right this seems to solve the problem described in #64, but this commit doesn't seem to fix the problem that both windows are opened on the same screen.

Greetings
Marc

**Comment by simonnagl** [comment]
> I checked out 42e9f76 with git checkout 42e9f76 and rebuilt pdfpc with make.
> You're right this seems to solve the problem described in #64, but this commit doesn't seem to fix the problem that both windows are opened on the same screen.

Thank you for testing. I will check if I can reproduce this till the end of the week.

**Comment by madoar** [comment]
Hi all,
yesterday I held a presentation with my laptop on a beamer and it worked just fine.
It seems that the reason for this strange phenomenon is my Setup at home.
For the test that produced this phenomenon I plugged my second monitor which is also connected to my main computer in my laptop. This means that it's connected to both my normal pc and my laptop at the same time, because it has both an DVI and VGA port and a selection button for the input signal which will be shown on the monitor. 
On my normal pc which is connected via DVI to the monitor the presentation worked just fine.
But on my laptop, which is connected via a mini displayport -> VGA adapter to my monitor, both windows opened on the external monitor.
The monitor is a SyncMaster T220 from Samsung.

Greetings
Marc

**Comment by AndreasBilke** [comment]
Do you have any chance to test the setup "laptop -> mini-displayport -> VGA
adapter" on a different screen/beamer?

**Comment by madoar** [comment]
Hi,
sry for the late reply.
I'll test it today or tomorrow with a few other monitors.

Greetings
Marc

**Comment by madoar** [comment]
Sorry for the late answer.
I tested the version on two different additional monitors and didn't see the effect again.
So I believe it's because of my setup with my monitor being connected to my normal pc and my laptop at the same time.
