### ISSUE TITLE
Pdfpc freezes on slides with a video

### ISSUE THREAD

**Issue by ZacharieALES** [pdfpc/pdfpc#525]
Hello,
I am using pdfpc to visualize a pdf presentation made with the beamer package of latex. The pdf file includes videos.

**Steps to reproduce**
Here is a minimalistic pdf file which produces the bug:
https://we.tl/t-WwuzQfsY13

The archive also includes:
- the tex source;
- the video file;
- the image.

To reproduce, open the pdf with pdfpc. Alternate between slide 1 and slide 2 using the left and right arrow until it freezes (the time varies but usally in less than 15 seconds).

The bug only seems to be produced when one of the 2 slides includes a video.
If I alternate between 2 slides without a video nothing happens (even if the pdf contains a video in another slide).

pdfpc version: 4.1
Used Distribution (GTK version, vala version): Linux Mint 19.3
Display Server (X/Wayland): Xorg
HiDPI Setting (yes/no): I don't know how to find the information.

EDIT: The bug does not occur on my laptop which is also using Linux Mint 19.3, Xorg and pdfpc version 4.1

**Comment by fnevgeny** [comment]
Hello,
We are at version 4.4 currently. 4.1 is hopelessly old. I believe the bug was fixed long ago.

**Comment by ZacharieALES** [comment]
Thank you for your answer. I updated pdfpc to version 4.4 and I still have the problem unfortunately.

**Comment by fnevgeny** [comment]
I cannot reproduce the problem. Sorry to ask, but are you 100% certain you run 4.4 indeed and not the system-installed 4.1?

**Comment by ZacharieALES** [comment]
To be sure I made a video where I first display the version and then make it freeze:
https://drive.google.com/file/d/14TttSroy481XLikILqYFdWqm_X_K_v51/view?usp=sharing

Don't hesitate to tell me if I done anything wrong.

**Comment by ZacharieALES** [comment]
I tried again on my laptop with version 4.5pre of pdfpc. It took more time but in the end it froze. However, this time only the pdfpc window froze and I was able to see what seems to be an infinite loop of the same error message:
`(pdfpc:12311): GStreamer-CRITICAL **:11:09:xx:yyy: gst_poll_read_control: assertion 'set != NULL' failed`

The value of the time "11:09:xx:yyy" was different in each message (like a chronometer).

**Comment by fnevgeny** [comment]
Well, I've spent half an hour in total frantically pressing the left/right arrows on three different computers... nada. Maybe I just cannot do it fast enough :) All these computers run the latest Ubuntu, though.

May I ask you to boot off a Ubuntu 20.04 live stick and try pdfpc from there (you can install software while "testing").

BTW, I didn't understand this:

> However, this time only the pdfpc window froze 

What is the difference? What else froze in the first case?

**Comment by ZacharieALES** [comment]
> Well, I've spent half an hour in total frantically pressing the
left/right arrows on three different computers... nada.

:) sorry for that.

> May I ask you to boot off a Ubuntu 20.04 live stick and try pdfpc from
there (you can install software while "testing").

Ok I will try

> What is the difference? What else froze in the first case?

The whole interface was frozen. I was not able to move the mouse or do
anything with the keyboard (even Ctrl + alt + F1 to switch to a session in
the console was not working).

Thank you for your help.

**Comment by einhander** [comment]
@ZacharieALES check gstreamer libs, video playback and hardware stability. Also check kernel log of previous boot, there maybe a clue to system freeze. Very likely it's bug video driver. Any user programs shouldn't freeze the system.

**Comment by ZacharieALES** [comment]
I installed nvidia's driver instead of the open-source driver and it seems to have solved the problem!

I wasn't using it previously as it made my computer boot in secure mode. The solution was to disable the secure boot in the bios...

**Comment by fnevgeny** [comment]
FWIW, my workstation uses the nouveau driver (version 20.0.4) with no problem. Can be a specific combination of software&hardware that triggered the bug in your case, of course.

So I close the ticket.
