### ISSUE TITLE
Unable to play movies

### ISSUE THREAD

**Issue by ziotom78** [pdfpc/pdfpc#87]
Pdfpc is not able to play the movie in the PDF file available at https://dl.dropboxusercontent.com/u/27308314/test.pdf (source: https://dl.dropboxusercontent.com/u/27308314/test.tex). I do not post the movie, as the problem lies *before* pdfpc actually attempts to play it. When the slide with the movie is displayed, the following warning appears:

    ** (pdfpc:16305): CRITICAL **: pdfpc_movie_filename_to_uri: assertion 'pdf_url != NULL' failed

I suspect commit 5a429bccabb7fce87eccd51779bac16a4c60f484 has something to do, as any statement that initialized `pdf_url` disappeared from the code, despite the fact that `Movie.new_from_link_mapping` requests an Uri (https://github.com/pdfpc/pdfpc/blob/master/src/classes/action/movie.vala#L163).

**Comment by AndreasBilke** [comment]
Thanks for your bug report. Could you test pull request #88? This should solve the issue.

**Comment by ziotom78** [comment]
Hi @AndreasBilke , I got the PR and compiled it successfully, but now there is another error (the video still doesn't play):

    Gstreamer error Resource not found.

I put some `warning` here and there and discovered that `Glib.Path.build_filename` (https://github.com/AndreasBilke/pdfpc/commit/88599a745fc3c75bfa960c31055cea6c3c0c41bd#diff-370ab09e1a3f00d27df08cf5a25ef573R334) seems to crunch the double slash in `file://`, as the following simple program shows (sorry, I do not know Vala, so I used C here):

`````c
#include <stdio.h>
#include <glib.h>

int main(void) {
  gchar *str = g_build_filename("file://", "/usr/bin/", "emacs", NULL);
  printf("filename: \"%s\"\n", str);
  return 0;
}
`````

The output is:

    filename: "file:/usr/bin/emacs"

**Comment by AndreasBilke** [comment]
I changed the pull request. The file:// prefix is now enforced.

**Comment by ziotom78** [comment]
It is strange, now the error message is different (still, the movie doesn't play):

    Gstreamer error Could not open resource for reading.

(Note that if I fire Evince and click on the slide, the "Parole" media player is called and the movie actually starts, so I do not think it is a problem in the file path.)

**Comment by AndreasBilke** [comment]
Could you post your current tex file? I tried your first example and for me
it worked always.

Am please give some information about your environment (linux distribution
etc.)

**Comment by ziotom78** [comment]
That's strange, in my case Evince works, but `pdfpc` does not. The LaTeX file I use is still my first example

````latex
\documentclass[italian,14pt]{beamer}
\mode<presentation>
\usepackage{hyperref}

\begin{document}

\begin{frame}{Test}

  \begin{center}
    \href{run:./volcano-eruption.mp4}{Click me!}
  \end{center}
  
\end{frame}

\end{document}
````

I tried changing the `.mp4` video with something else (just `cp MY_OTHER_VIDEO volcano-eruption.mp4` to overwrite the old file), but the problem still persists.

My configuration is the following:
- Linux Xubuntu 64-bit 15.10 (just upgraded from 15.04), running Xfce 4.12
- Valac 0.29.2
- Gcc 5.2.1

The output of `cmake` is the following:

`````
-- The C compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Vala: /usr/local/bin/valac (found suitable version "0.29.2", minimum required is "0.26") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- checking for module 'gobject-2.0'
--   found gobject-2.0, version 2.46.1
-- checking for module 'gio-2.0'
--   found gio-2.0, version 2.46.1
-- checking for module 'gee-0.8'
--   found gee-0.8, version 0.18.0
-- checking for module 'poppler-glib'
--   found poppler-glib, version 0.33.0
-- checking for module 'gtk+-3.0'
--   found gtk+-3.0, version 3.16.7
-- checking for module 'gthread-2.0'
--   found gthread-2.0, version 2.46.1
-- checking for module 'gstreamer-1.0'
--   found gstreamer-1.0, version 1.6.0
-- checking for module 'gstreamer-base-1.0'
--   found gstreamer-base-1.0, version 1.6.0
-- checking for module 'gstreamer-audio-1.0'
--   found gstreamer-audio-1.0, version 1.6.0
-- checking for module 'gstreamer-video-1.0'
--   found gstreamer-video-1.0, version 1.6.0
-- checking for module 'gdk-x11-3.0'
--   found gdk-x11-3.0, version 3.16.7
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tomasi/Projects/ab_pdfpc/pdfpc/build
`````

**Comment by ziotom78** [comment]
I forgot to mention that if I install `pdfpc` from the Ubuntu 15.10 repositories (`apt-get install pdf-presenter-console`), the file works fine. Here are a few details about the Ubuntu package:

`````
$ /usr/bin/pdfpc --version

** (pdfpc:17789): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
pdfpc v4.0
(C) 2015 Robert Schroll, Andreas Bilke, Andy Barry and others
(C) 2012 David Vilar
(C) 2009-2011 Jakob Westhoff

License GPLv2: GNU GPL version 2 <http://gnu.org/licenses/gpl-2.0.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ apt-cache show pdf-presenter-console
Package: pdf-presenter-console
Priority: extra
Section: universe/graphics
Installed-Size: 469
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Barak A. Pearlmutter <bap@debian.org>
Architecture: amd64
Version: 4.0.0-1
Provides: pdfpc
Depends: libc6 (>= 2.4), libcairo2 (>= 1.2.4), libgdk-pixbuf2.0-0 (>= 2.22.0), libgee-0.8-2 (>= 0.8.3), libglib2.0-0 (>= 2.37.3), libgstreamer-plugins-base1.0-0 (>= 1.0.0), libgstreamer1.0-0 (>= 1.0.0), libgtk-3-0 (>= 3.9.10), libpango-1.0-0 (>= 1.14.0), libpoppler-glib8 (>= 0.18.0)
Filename: pool/universe/p/pdf-presenter-console/pdf-presenter-console_4.0.0-1_amd64.deb
Size: 98246
MD5sum: 34d7233beb989fcc2d0178f7c0e794cc
SHA1: 67bb8eb4cae28d77174294740d6f56e3034d05a0
SHA256: 73e8cffd3fb850b5b9859315a79465781093af8e53e18515008d9dc1924a0ad6
Description-en: multi-monitor presentation tool (ala Keynote) for PDF files
 PPC is a viewer for PDF which uses Keynote-like multi-monitor output
 to provide meta information to the speaker.  It can show a normal
 presentation window on one screen and a more sophisticated overview
 on the other, with information like a picture of the next slide and a
 clock with the time remaining.
Description-md5: 5df0b8af9ac469320876a53b4d65aa23
Homepage: http://pdfpc.github.io/pdfpc/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
`````

**Comment by AndreasBilke** [comment]
The working pdf-presenter-console from the ubuntu repos was expected, since
I broke the video code with my changes in the note font size feature (and
this is not included in the repos so far).

Could you apply the following patch to the current HEAD of the issue-87
branch? (pull request):

```
diff --git a/src/classes/action/movie.vala b/src/classes/action/movie.vala
index 1b95213..933072f 100644
--- a/src/classes/action/movie.vala
+++ b/src/classes/action/movie.vala
@@ -161,6 +161,7 @@ namespace pdfpc {
                 }
             }
             string uri = filename_to_uri(file, controller.get_pdf_fname());
+            stdout.printf("uri %s\n", uri);
             bool uncertain;
             string ctype = GLib.ContentType.guess(uri, null, out uncertain);
             if (!("video" in ctype))

```

This just prints the generated URI for the movie. For your tex example I
get

$ bin/pdfpc ~/Downloads/test.pdf
uri file:///home/bilke/Downloads/./volcano-eruption.mp4

Could you check that the file at this position exists?

**Comment by ziotom78** [comment]
That's curious, my URI is different, because it does not contain the full path but the relative path. Might this be a sign of the cause of the problem?

    uri file://./volcano-eruption.mp4

Yesterday I already put a `printf` call after the call to `filename_to_uri`, but I was not surprised of the result because I saw the same (relative) path I put in the `test.tex` file.

(P.S. The file exists, as I can see it by running `ls`; moreover, Evince opens it properly. If I manually math the URI printed by `pdfpc` absolute and copy the url `file:///home/tomasi/volcano-eruption.mp4` in Firefox, the file starts playing regularly.)

**Comment by ziotom78** [comment]
Ok, I confirm this is the problem. If I change the file `test.tex` so that it contains the *absolute path* to the file, `pdfpc` no longer has problems:

`````latex
\documentclass[italian,14pt]{beamer}
\mode<presentation>
\usepackage{hyperref}

\begin{document}

\begin{frame}{Test}

  \begin{center}
    \href{run:/home/tomasi/volcano-eruption.mp4}{Click me!}
  \end{center}
  
\end{frame}

\end{document}
`````

**Comment by ziotom78** [comment]
The following patch makes `pdfpc` work even with relative paths:
`````
@@ -331,8 +331,8 @@ namespace pdfpc {
             if (GLib.Path.is_absolute(file))
                 return "file://" + file;
             string dirname = GLib.Path.get_dirname(pdf_fname);
-
-            return "file://" + GLib.Path.build_filename(dirname, file);
+           string filename = Posix.realpath(GLib.Path.build_filename(dirname, file));
+           return "file://" + filename;
`````

**Comment by AndreasBilke** [comment]
I pushed the changes. Does it work for you now with relativ and full paths?

**Comment by ziotom78** [comment]
Yes, it does. Now everything runs smoothly. Thanks a lot!
